name: "diff-releases"
version: 0.0.24
usage: "helm get templates "
description: |-
  diff-releases WHAT [--code] --release1 RELEASE1 --revision1 R1 [--namespace1 NAMESPACE1] --release2 RELEASE2 --revision2 R2 [--namespace2 NAMESPACE2]
  where WHAT is:
  comma separated (no space before or after commas) set of some of these options hooks, manifest, notes, values, templates
  --code option specifies to use VSCode to show the diff
platformCommand:
  - os: linux
    arch: amd64
    command: "$HELM_PLUGIN_DIR/bin/diff-releases"
  - os: windows
    arch: amd64
    command: "$HELM_PLUGIN_DIR\\bin\\diff-releases.exe"
